### ISSUE TITLE
Clicking on Home or the logo should load the landing page whether logged in or not

### ISSUE THREAD

**Issue by DeckOfPandas** [takeyourmeds/takeyourmeds-web#109]
@lamby ? I saw you wired things up this way deliberately, so do you disagree?

**Comment by lamby** [comment]
Yes quite strongly disagre. I believe to show the landing page is broken UI:
- It requires an additional link to the logged-_in_ dashboard
- The copy is generally geared around promoting registration which is pointless if you are logged-in, and/or compromises are required to make it serve double-duty.
- It implies that you are logged-out, which is false.
- Regardless of any of the above or other objections, it is not the typical behaviour of websites and thus misleading to the regular internet user (eg. go to gmail.com whilst logged-in, etc.)

**Comment by DeckOfPandas** [comment]
Okay, I can follow this. I guess I was coming up against it in a way a normal user wasn't because I was clicking around checking all the pictures looked okay etc.

I can agree with you, so will close this.
