### ISSUE TITLE
I have to click "forgot password" every time

### ISSUE THREAD

**Issue by DeckOfPandas** [takeyourmeds/takeyourmeds-web#150]

**Comment by DeckOfPandas** [comment]
@lamby 

My email address is helen@deckofpandas.co.uk

I tried to log in, and saw the red error message: "Please enter a valid email address and password"

I clicked "Forgot password", received the email, clicked on the link and entered the new password "hellohelen"

I clicked logout, then login, and entered my email address and "hellohelen" as the password

I saw the red error message again: "Please enter a valid email address and password"

**Comment by DeckOfPandas** [comment]
This has happened four times in a row

**Comment by lamby** [comment]
Please don't forget to assign back otherwise it's not on my list of tickets! ;)
