### ISSUE TITLE
Clean up configuration of telephony app

### ISSUE THREAD

**Issue by rossjones** [takeyourmeds/takeyourmeds-web#19]
The telephony app (twilio wrapper) currently has only a single set of auth details.  To make testing easier/better we should change the things included in local_settings to have a DATABASES style dict so we can use actual test details from twilio for testing.

**Comment by rossjones** [comment]
Fixed and merged in e7ce30c

**Comment by DeckOfPandas** [comment]
Thanks!

**Comment by DeckOfPandas** [comment]
I pulled your changes, and re-added my own Twilio details to
local_settings.py, then ran python manage.py migrate, but got this:
"NameError: name 'TWILIO_CONFIGS' is not defined"

local_settings.py has "TWILIO_CONFIG = TWILIO_CONFIGS["default"]". What
should it have?

**Comment by rossjones** [comment]
Typo in the sample :(

```
TWILIO_CONFIGS = {
    #"test": {
    #    # You can retrieve these settings from
    #    # https://www.twilio.com/user/account/developer-tools/test-credentials
    #    "ACCOUNT_SID": "",
    #    "AUTH_TOKEN": "",
    #    "FROM_NUMBER": "+15005550006",
    #    "ROOT_URL": "http://127.0.0.1:8000/telephony/info"
    #},
    "default": {
        "ACCOUNT_SID": "XXX", # Your Twilio account SID
        "AUTH_TOKEN": "XXX",  # Your twilio account SID
        "FROM_NUMBER": "0000",  # Your twilio SMS-enabled phone number
        # The root URL from where the Twilio service can pick
        # up the TwilML because Ross is too lazy to work out the
        # server name dynamically.
        "ROOT_URL": "http://127.0.0.1:8000/telephony/info"
    }
}
TWILIO_CONFIG = TWILIO_CONFIGS["default"]
```

**Comment by DeckOfPandas** [comment]
Ahhhhh thank you!

**Comment by lamby** [comment]
This is related to #57

**Comment by lamby** [comment]
Done on https://github.com/lamby/takeyourmeds-web/tree/cleanup
