### ISSUE TITLE
User's telephone number should be required.

### ISSUE THREAD

**Issue by rossjones** [takeyourmeds/takeyourmeds-web#21]
If we ask users signing up we can:
- Use the number to send a validation pin ...
- Receive calls from that user to record the voice message ...
- Allow callbacks to that number if the reminder recipient wants to call ...

**Comment by symroe** [comment]
Twilio have just launched a few new things, including:

https://www.twilio.com/authy

**Comment by DeckOfPandas** [comment]
I'm closing this because the points are included above
(Above is just a brain dump and will get reorganised, but it's enough for now)
