### ISSUE TITLE
Integrate design from wrapbootstrap.com

### ISSUE THREAD

**Issue by DeckOfPandas** [takeyourmeds/takeyourmeds-web#38]
http://wrapbootstrap.com/preview/WB05F069P is winning for me atm

**Comment by lamby** [comment]
Please buy it and send me the zipfile.

**Comment by lamby** [comment]
... mentioning any particular sub-variant of that theme, etc. etc.

**Comment by DeckOfPandas** [comment]
Done, see email for authentication details

(Can you close this when relevant please)

**Comment by lamby** [comment]
Adding to milestone- forgot to

**Comment by DeckOfPandas** [comment]
I need to decide on the different page layouts: the subvariant I mentioned
in the email (boxed) is just for the front page.

**Comment by lamby** [comment]
Ping on this

**Comment by DeckOfPandas** [comment]
Will do tomorrow morning.

**Comment by lamby** [comment]
> Will do tomorrow morning.

Ping on this?

**Comment by DeckOfPandas** [comment]
I have detailed chosen pages in the email I just sent (or have tried to)

**Comment by lamby** [comment]
Please copy the email into a ticket to avoid multiple comm channels. This will will do, another preferable.

**Comment by lamby** [comment]
```
From: Helen Jackson <helen@helenjackson.co.uk>
Date: Wed, 14 Oct 2015 20:55:36 +0100
Subject: TYM website pages based on Assan template
To: Chris Lamb <chris@chris-lamb.co.uk>

#Navbar (from left to right):

(icon and name from current site, which links to index)

"About"

"FAQs"

"Contact"

"Login/Register"+(padlock icon) 
    If not logged in, clicking shows the dropdown login box that appears if you click on (padlock)+"Login" next to the phone number on the top bar of the template site; user can then click "Log in" or "Sign up"
        "Log in" logs user in and shows dashboard
        "Sign up" shows SHOP --> Register with username and password prefilled
    If logged in, show dropdown menu --> "Dashboard" : "New reminder" : "Log out"


#Pages (pointing at things from Assan template)

Index: boxed
    "What we offer" replaced with the three side-by-side paragraphs beginning "customisable schedule" (icons don't matter as I can fix this)

About: PAGES --> About
    With PAGES --> Our Team at the bottom

FAQs: new page: PAGES --> FAQs
    Text of lorem ipsum is fine for now

Contact: new page: PAGES --> Contact Option

Login/Register: 
    Signup page from SHOP --> Register, without gender but with phone number

Dashboard: new page, structure tbc

New reminder: no idea...hm


#Breadcrumbs

Header: FEATURES --> Headers --> Header 1 - Default

Footer: FEATURES --> Footers --> Footer Dark - 2

No search icon
```

**Comment by lamby** [comment]
> clicking shows the dropdown login box that appears if you click on (padlock)+"Login" next to the phone number on the top bar of the template site

Whilst a "neat" widget this is actually a bad idea it has rather poor UX on tablets and phone. We need a styled "login" page anyway, due to -- for example -- needing somewhere sane to redirect to if the user gets logged out and tries to go to eg. `/reminders/create`.

**Comment by lamby** [comment]
Closing; have split into separate tickets.
