### ISSUE TITLE
Remove ngrok requirement for tests

### ISSUE THREAD

**Issue by DeckOfPandas** [takeyourmeds/takeyourmeds-web#40]
Am currently hacking some ssh port forwarding because twilio needs to be able get callbacks from the client
(pretend those words make sense)

**Comment by lamby** [comment]
I'll have a think about the best way of doing this. As in, whilst having a local environment entirely self-contained is nice, if it can't perform side effects with Twilio one can't really test calls. But _requiring_ that locally sucks. And automated tests need to run without calling folks or requiring the internet at all (lol #18)

(Note that using Twilio _locally_ taints the idea of using Twilio's logs from the live site as they'll be mixed with local testing etc.)

**Comment by lamby** [comment]
On https://github.com/lamby/takeyourmeds-web/tree/cleanup, under local and test roles Twilio is actually "faked" with fake sids that are saved.
