### ISSUE TITLE
Staging system

### ISSUE THREAD

**Issue by DeckOfPandas** [takeyourmeds/takeyourmeds-web#41]
i.e. local --> test.takeyourmeds.co.uk -->  live

**Comment by lamby** [comment]
My suggestion is to have:
- `master`` deploys to staging
- a `live` branch deploys to live.

I usually prefer swapping this around (ie. with a `staging` branch) but GitHub PRs make it somewhat too easy (from a good UX PoV) to merge things to master, so queuing up 4 or 5 changes for release somewhat implies the above.

Testing locally (ngrok, whatever) is, IMHO, entirely separate to this.

**Comment by lamby** [comment]
From phone call: going with this ^

**Comment by DeckOfPandas** [comment]
Great

**Comment by lamby** [comment]
Blocked by #63, or at least temporarily (no point working on alternative whilst waiting for reply).

**Comment by lamby** [comment]
May not be possible to have a `live` branch - rather manual deployment from deployhq will be required due to their lameness. :(

Still, lots of progress today and looking good.

**Comment by lamby** [comment]
deployhq is bucket of fail so I can either get the master deploying to stage _or_ live deploying.

Closing for now; will think of a different solution.
