### ISSUE TITLE
Deal with subscription ID returned from Stripe

### ISSUE THREAD

**Issue by DeckOfPandas** [takeyourmeds/takeyourmeds-web#43]

**Comment by lamby** [comment]
I assume this means actually associating it with a user?

**Comment by lamby** [comment]
(see also "account" parent discussion)

**Comment by DeckOfPandas** [comment]
As or phonecall, we need a good noun for "group of patients of common
provenance", but when we have one then a Stripe ID should be associated
with it.

**Comment by lamby** [comment]
dupe
