### ISSUE TITLE
Sort out headings on navbar

### ISSUE THREAD

**Issue by DeckOfPandas** [takeyourmeds/takeyourmeds-web#51]
Currently a bit mad

**Comment by lamby** [comment]
This seems like it could be merged with #38 in that fixing that would implicily fix this

**Comment by DeckOfPandas** [comment]
Yes, gone.

**Comment by DeckOfPandas** [comment]
List and behaviour sent in email

**Comment by lamby** [comment]
Please copy into a ticket - I don't think we want multiple comm channels. (And hey, we're open sauce..)

**Comment by lamby** [comment]
Closing and merging with #38
