### ISSUE TITLE
Get another server on retrosnub account

### ISSUE THREAD

**Issue by lamby** [takeyourmeds/takeyourmeds-web#63]

**Comment by DeckOfPandas** [comment]
Have enquired. Will update when possible.

**Comment by lamby** [comment]
This blocks #41, or at least temporarily (no point working on alternative whilst waiting for reply).

**Comment by lamby** [comment]
Can I ping you on this? Thanks :)

**Comment by lamby** [comment]
Taken over this and got the new server

**Comment by DeckOfPandas** [comment]
Yeah, unfortunately haven't had a reply from my VPS provider. Let me know
what you need here (including advice to migrate the whole thing to heroku)

**Comment by pacharanero** [comment]
Or Digital Ocean, I've had a good service from them for the last year with
the CCIO net on Discourse

**Comment by lamby** [comment]
> Yeah, unfortunately haven't had a reply from my VPS provider

Huh? I got in touch with Retrosnub myself. It's all sorted.
