### ISSUE TITLE
Move from username → email

### ISSUE THREAD

**Issue by lamby** [takeyourmeds/takeyourmeds-web#75]
This came out of looking at #38 more carefully. Not sure why I didn't spot it before, apologies for that.

Ideally, I think we should just have email; fewer things are better (although in Django this is slightly more work). Usernames are nice vanity things, but TYM is a private service, not a social one, and it's just something else to forget.

**Comment by DeckOfPandas** [comment]
Totally agree. I hate usernames anyway.

**Comment by lamby** [comment]
Merged to `new-design`
